---
name: "🐛 Bug Report"
description: Report a bug
title: "(API name): (short issue description)"
labels: [bug]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened?

        Please include full errors, uncaught exceptions, stack traces, and relevant logs.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: |
        Anything else that might be relevant for troubleshooting this bug.
    validations:
      required: false
